### ISSUE TITLE
Setting to break words longer than target width

### ISSUE THREAD

**Issue by callum-oakley** [jtdaugherty/word-wrap#3]
In some situations, the target width is a hard limit that shouldn't be exceeded, even if a single word is longer than that limit, so the word should be broken up. (happens with long URLs in markdown files for example). Of course sometimes the current behaviour is the desired behaviour, so this seems like a good candidate for another setting in `WrapSettings`

**Comment by jtdaugherty** [comment]
Released in `0.3`.
